const HARNESS_EVENT_KINDS = [
  "harness.queued",
  "harness.dispatched",
  "harness.stop_requested",
  "harness.instruction_queued",
  "harness.instruction_applied",
  "harness.instruction_discarded",
] as const;

/** 服务端 projection 公开的全部 SSE event kind（不含 sdk.output_rejected）。 */
export const RUN_EVENT_KINDS = [
  "run.created",
  ...HARNESS_EVENT_KINDS,
  "tool.evidence_recorded",
  "tool.evidence_dropped",
  "artifact.published",
  "attempt.failed",
  "run.failed",
  "run.review_rejected",
  "run.completed",
  "attempt.started",
  "attempt.transition_rejected",
  "run.transition_rejected",
  "subagent.started",
  "subagent.ended",
  "feedback.received",
  "revision.applied",
  "evaluation.round",
  "verification.references",
  "campaign.prior_attempts",
  "campaign.memory_degraded",
  "artifact.field_overwritten",
  "sdk.structured_correction",
  "sdk.usage",
  "sdk.trace.started",
  "sdk.trace.agent_started",
  "sdk.trace.agent_ended",
  "sdk.trace.tool_started",
  "sdk.trace.tool_ended",
  "sdk.trace.ended",
  "sdk.trace.callback_error",
] as const;

/** 生命周期、指令及工具进度变化均唤醒 UI 回源快照。 */
export const UI_SSE_EVENT_KINDS = [
  "sdk.trace.started",
  "sdk.trace.tool_started",
  "sdk.trace.tool_ended",
  "sdk.trace.ended",
  "run.created",
  ...HARNESS_EVENT_KINDS,
  "attempt.started",
  "subagent.started",
  "subagent.ended",
  "feedback.received",
  "revision.applied",
  "tool.evidence_recorded",
  "sdk.structured_correction",
  "artifact.published",
  "attempt.failed",
  "run.completed",
  "run.review_rejected",
  "run.failed",
] as const;

export const TERMINAL_SSE_EVENT_KINDS = ["run.completed", "run.failed", "run.review_rejected"] as const;
