// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { RunApiRunsIdentifierGetData, RunApiRunsIdentifierGetErrors, RunApiRunsIdentifierGetResponses, RunsApiRunsGetData, RunsApiRunsGetErrors, RunsApiRunsGetResponses, Science125ApiScience125GetData, Science125ApiScience125GetResponses, StartBatchApiBatchPostData, StartBatchApiBatchPostResponses, StartRunApiRunsPostData, StartRunApiRunsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Science125
 */
export const science125ApiScience125Get = <ThrowOnError extends boolean = false>(options?: Options<Science125ApiScience125GetData, ThrowOnError>): RequestResult<Science125ApiScience125GetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<Science125ApiScience125GetResponses, unknown, ThrowOnError>({ url: '/api/science125', ...options });

/**
 * Runs
 */
export const runsApiRunsGet = <ThrowOnError extends boolean = false>(options?: Options<RunsApiRunsGetData, ThrowOnError>): RequestResult<RunsApiRunsGetResponses, RunsApiRunsGetErrors, ThrowOnError> => (options?.client ?? client).get<RunsApiRunsGetResponses, RunsApiRunsGetErrors, ThrowOnError>({ url: '/api/runs', ...options });

/**
 * Start Run
 */
export const startRunApiRunsPost = <ThrowOnError extends boolean = false>(options?: Options<StartRunApiRunsPostData, ThrowOnError>): RequestResult<StartRunApiRunsPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<StartRunApiRunsPostResponses, unknown, ThrowOnError>({ url: '/api/runs', ...options });

/**
 * Start Batch
 *
 * 发起一次串行批跑。
 *
 * 单写者锁保证同时最多一个可变 run，所以「跑多题」只能是一个串行任务，不是并发。
 * 这里把网页上的多选交给既有的 `app.batch`（断点续跑、熔断、分类 tally 都在那边），
 * 自己不记任何批次状态：进度由 `/batch` 页从 runs/ 派生。
 */
export const startBatchApiBatchPost = <ThrowOnError extends boolean = false>(options?: Options<StartBatchApiBatchPostData, ThrowOnError>): RequestResult<StartBatchApiBatchPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<StartBatchApiBatchPostResponses, unknown, ThrowOnError>({ url: '/api/batch', ...options });

/**
 * Run
 */
export const runApiRunsIdentifierGet = <ThrowOnError extends boolean = false>(options: Options<RunApiRunsIdentifierGetData, ThrowOnError>): RequestResult<RunApiRunsIdentifierGetResponses, RunApiRunsIdentifierGetErrors, ThrowOnError> => (options.client ?? client).get<RunApiRunsIdentifierGetResponses, RunApiRunsIdentifierGetErrors, ThrowOnError>({ url: '/api/runs/{identifier}', ...options });
