// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type Science125ApiScience125GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/science125';
};

export type Science125ApiScience125GetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunsApiRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: string | null;
    };
    url: '/api/runs';
};

export type RunsApiRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunsApiRunsGetError = RunsApiRunsGetErrors[keyof RunsApiRunsGetErrors];

export type RunsApiRunsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StartRunApiRunsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runs';
};

export type StartRunApiRunsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunApiRunsIdentifierGetData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: string;
    };
    query?: {
        /**
         * View
         */
        view?: string | null;
        /**
         * Artifact
         */
        artifact?: string | null;
    };
    url: '/api/runs/{identifier}';
};

export type RunApiRunsIdentifierGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunApiRunsIdentifierGetError = RunApiRunsIdentifierGetErrors[keyof RunApiRunsIdentifierGetErrors];

export type RunApiRunsIdentifierGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
