/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutBatchRouteImport } from './routes/_layout/batch'
import { Route as LayoutRunsIndexRouteImport } from './routes/_layout/runs.index'
import { Route as LayoutRunsRunIdRouteImport } from './routes/_layout/runs.$runId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBatchRoute = LayoutBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsIndexRoute = LayoutRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsRunIdRoute = LayoutRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/batch': typeof LayoutBatchRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
  '/runs/': typeof LayoutRunsIndexRoute
}
export interface FileRoutesByTo {
  '/batch': typeof LayoutBatchRoute
  '/': typeof LayoutIndexRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
  '/runs': typeof LayoutRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/batch': typeof LayoutBatchRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/runs/$runId': typeof LayoutRunsRunIdRoute
  '/_layout/runs/': typeof LayoutRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batch' | '/runs/$runId' | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/batch' | '/' | '/runs/$runId' | '/runs'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/batch'
    | '/_layout/'
    | '/_layout/runs/$runId'
    | '/_layout/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/batch': {
      id: '/_layout/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof LayoutBatchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs/': {
      id: '/_layout/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof LayoutRunsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs/$runId': {
      id: '/_layout/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof LayoutRunsRunIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBatchRoute: typeof LayoutBatchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutRunsRunIdRoute: typeof LayoutRunsRunIdRoute
  LayoutRunsIndexRoute: typeof LayoutRunsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBatchRoute: LayoutBatchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutRunsRunIdRoute: LayoutRunsRunIdRoute,
  LayoutRunsIndexRoute: LayoutRunsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
