import type { PublicArtifact } from "./projection.ts";

export type PublicResearchPlan = Extract<PublicArtifact["content"], { artifact_type: "research-plan" }>;

/** 把已通过公共白名单的 ResearchPlan 投影成确定性的提交材料草稿。 */
export function renderResearchPlanMarkdown(plan: PublicResearchPlan): string {
  const lines = [
    `# ${plan.paper_title}`,
    "",
    "## Problem statement",
    plan.problem_statement,
    "",
    "## Rationale",
    plan.rationale,
    "",
    "## Technical details",
    plan.technical_details,
    "",
    "## Datasets",
    ...plan.datasets.map((dataset) => `- ${dataset}`),
    "",
    "## Source",
    plan.source,
    "",
    "## Target",
    plan.target,
    "",
    "## Executable research plan",
    "### Predictions",
    ...plan.execution_plan.predictions.map(
      (item) => `- [${item.candidate_id}] ${item.prediction}（证伪条件：${item.falsification_criterion}）`,
    ),
    "",
    "### Data and conditions",
    ...plan.execution_plan.data_requirements.map(
      (item) => `- ${item.source}；变量：${item.variables.join("、")}；条件：${item.conditions.join("；")}`,
    ),
    "",
    "### Steps",
    ...plan.execution_plan.steps.map((item) => `${item.order}. ${item.action} → ${item.expected_output}`),
    "",
    "### Analysis",
    ...plan.execution_plan.analysis.map(
      (item) => `- ${item.method}；输入：${item.inputs.join("、")}；决策规则：${item.decision_rule}`,
    ),
    "",
    "### Result interpretations",
    ...plan.execution_plan.result_interpretations.map((item) => `- ${item.observed_result} → ${item.meaning}`),
    "",
    "### Stop / rollback / supplement",
    `- 停止：${plan.execution_plan.stop_conditions.join("；")}`,
    `- 回退：${plan.execution_plan.rollback_conditions.join("；")}`,
    `- 补证：${plan.execution_plan.supplement_evidence_conditions.join("；")}`,
    "",
    "## Paper abstract",
    plan.paper_abstract,
    "",
    "## Methods",
    plan.methods,
    "",
    "## Experiments",
    `### Design\n${plan.experiments.design}`,
    "",
    "### Baselines",
    ...plan.experiments.baselines.map((item) => `- ${item.name} [${item.evidence_id}]`),
    "",
    "### Metrics",
    ...plan.experiments.metrics.map((item) => `- ${item.name} [${item.evidence_id}]`),
    "",
    "## Results",
    `Status: ${plan.results.status}`,
    `Validation basis: ${plan.results.validation_basis}`,
    "",
    "Feasibility argument:",
    plan.results.feasibility_argument,
    "",
    ...plan.results.expected_outcomes.map((item) => `- ${item.metric}: ${item.statement}`),
    "",
    "## References",
    ...plan.references.map((reference) => `- ${reference}`),
    "",
  ];
  return lines.join("\n");
}
